version: '3.0'
services:
  zookeeper:
    image: bitnami/zookeeper:3.4.10 # HDI uses 3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    image: bitnami/kafka:2.1.1
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://${MY_IP}:9092,EXTERNAL://${MY_IP}:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
  postgresql:
    image: debezium/postgres:latest
    container_name: postgresql
    environment:
      - DEBUG=false
      - DB_USER=test
      - DB_PASS=Test123
      - DB_NAME=test
    ports:
      - "5432:5432"
  connect:
    image: debezium/connect:1.0
    container_name: connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - postgresql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses